services:
    postgres:
        image: 'postgres:18-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5439}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sail-postgresql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-postgresql:
        driver: local
